# Default values for cassandra-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: gcr.io/cassandra-operator/cassandra-operator
  tag: latest
  pullPolicy: Always

#imagePullSecrets: "regcred"

resources:
  limits:
    cpu: 200m
    memory: 100Mi
  requests:
    cpu: 100m
    memory: 50Mi

nodeSelector: {}

rbacEnable: true

pspEnable: true

tolerations: []

affinity: {}

namespace: "default"