apiVersion: v1
entries:
  cassandra:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-02-05T11:46:35.765276293+01:00"
    description: A Helm chart for creating Cassandra clusters using the Cassandra
      operator
    digest: 635f20e5345bdfde60063471a56890ace052b2d1fdcd204a93e0165607eb95c4
    home: https://www.instaclustr.com
    keywords:
    - operator
    - cassandra-operator
    - instaclustr
    maintainers:
    - name: Stefan Miklosovic
    - name: Alex Lourie
    - name: Ben Bromhead
    - name: Adam Zegelin
    name: cassandra
    sources:
    - https://github.com/instaclustr/cassandra-operator
    urls:
    - cassandra-1.0.0.tgz
    version: 1.0.0
  cassandra-operator:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-02-05T11:46:35.766075348+01:00"
    description: A Helm chart for Cassandra Operator for Kubernetes by Instaclustr
    digest: 2f996b9ea0b2fb72b10c27f3a3643a5747b5b3eec578fbb9ca1512763f4fe93c
    home: https://www.instaclustr.com
    keywords:
    - operator
    - cassandra-operator
    - instaclustr
    maintainers:
    - name: Stefan Miklosovic
    - name: Alex Lourie
    - name: Ben Bromhead
    - name: Adam Zegelin
    name: cassandra-operator
    sources:
    - https://github.com/instaclustr/cassandra-operator
    urls:
    - cassandra-operator-1.0.0.tgz
    version: 1.0.0
generated: "2020-02-05T11:46:35.764549708+01:00"
